### PR TITLE
Convert all performances in `Test_files`

### PR DESCRIPTION
**Pull request by probonopd**
When merged, this will:

* Convert all performances in `Test_files` using the `.sh` scripts provided in that directory
* Upload artifacts
* Create and upload to GitHub Releases

Here you can already see what it produces:
[performances.zip](https://github.com/probonopd/MDX_PerfConv/releases/download/continuous/performances.zip)

### CODE REVIEW

**Comment by probonopd** [comment]
To make this more useful, the `.sh` files in `Test_files` should be edited to use `-n` so that we only have one performance starting with the same number. I would recommend to do this in (reverse?) chronological order in which the instruments were released.

**Comment by probonopd** [comment]
To make this more useful, automatic `-n` numbering would be good to have in `MDX_PerfConv` so that the number would be automatically increased based on which files already exist in the current working directory. Also, the output files should be saved in the current working directory rather than in the same directory as the input files.

 This way, no values for `-n` would need to be hardcoded anywhere.

**Comment by BobanSpasic** [comment]
The output numbers are already too high, much higher than 256. I need to think about a solution.

**Comment by probonopd** [comment]
For now, we can use directories - let me try something... more soon.

**Comment by probonopd** [comment]
The converted files are now in folders, just like the input files.

**Pull request merged**
